/*
 * Define error code in this file
 */

#define TFTP_ERROR_INVALID_ARGUMENT_COUNT 11
#define TFTP_ERROR_INVALID_OPCODE 12

#define TFTP_ERROR_NOT_DEFINED 0
#define TFTP_ERROR_FILE_NOT_FOUND 1
#define TFTP_ERROR_ACCESS_VIOLATION 2
#define TFTP_ERROR_DISK_FULL 3
#define TFTP_ERROR_ILLEGAL_OPERATION 4
#define TFTP_ERROR_UNKNOWN_PORT_NUMBER 5
#define TFTP_ERROR_FILE_EXISTS 6
#define TFTP_ERROR_NO_SUCH_USER 7